name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r mlops-movie-recommendation/requirements.txt
          pip install -r mlops-movie-recommendation/requirements-dev.txt

      - name: Run pre-commit (black, isort, ruff)
        run: |
          pre-commit run --all-files --show-diff-on-failure

      - name: Run tests
        run: |
          pytest -q mlops-movie-recommendation/tests

  docker-build-push:
    needs: lint-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: wuxdas
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./mlops-movie-recommendation
          file: ./mlops-movie-recommendation/Dockerfile.api
          push: true
          tags: |
            wuxdas/mlops-movie-recommendation:latest
            wuxdas/mlops-movie-recommendation:${{ github.sha }}

      - name: Build and push Dashboard image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./mlops-movie-recommendation
          file: ./mlops-movie-recommendation/Dockerfile.dashboard
          push: true
          tags: |
            wuxdas/mlops-movie-recommendation-dashboard:latest
            wuxdas/mlops-movie-recommendation-dashboard:${{ github.sha }} 